# Generated by Django 5.2.3 on 2025-07-14 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_pressureadjustment_video_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pressureadjustment',
            name='after_level',
            field=models.IntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')]),
        ),
        migrations.AlterField(
            model_name='pressureadjustment',
            name='before_level',
            field=models.IntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')]),
        ),
        migrations.AlterField(
            model_name='pressureadjustment',
            name='method',
            field=models.CharField(choices=[('video', '视频疗法')], max_length=100),
        ),
        migrations.AlterField(
            model_name='pressureadjustment',
            name='video_title',
            field=models.CharField(default='', max_length=255, verbose_name='视频标题'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pressureadjustment',
            name='video_url',
            field=models.URLField(default='', verbose_name='视频链接'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pressuretest',
            name='pressure_level',
            field=models.IntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')]),
        ),
    ]
